import Head from 'next/head'
import Image from 'next/image'
// import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Banner from '../components/Banner'
// const inter = Inter({ subsets: ['latin'] })
import heroimage from '../public/static/3.1 heroimage.png'
import Card from '../components/Card'

export default function Home() {
  const handleOnBannerBtnClick = () => {
      console.log('hi banner button')
  };
  return (
    <>
      <Head>
        <title>Coffee Website </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Banner buttonText="View Stores nearby" handleOnClick={handleOnBannerBtnClick}/>
        <div className={styles.heroImage}>
            <Image width={700} height={400} src={heroimage}/>
        </div>
        <Card />
      </main>
    </>
  )
}
