import Head from "next/head";
import Image from "next/image";
// import { Inter } from '@next/font/google'
import styles from "../styles/Home.module.css";
import Banner from "../components/Banner";
// const inter = Inter({ subsets: ['latin'] })
import heroimage from "../public/static/3.1 heroimage.png";
import Card from "../components/Card";
import coffeeStoresData from "../data/5.1 coffee-stores.json";
import { fetchCoffeeStores} from '../lib/coffee-store'
export async function getStaticProps(context) {
  const coffeeStores = await fetchCoffeeStores();
  return {
    props: {
      coffeeStores: coffeeStores,
    },
  };
}

export default function Home(props) {
  console.log(props);
  const handleOnBannerBtnClick = () => {
    console.log("hi banner button");
  };
  return (
    <>
      <Head>
        <title>Coffee Website </title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Banner
          buttonText="View Stores nearby"
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image width={700} height={400} src={heroimage} />
        </div>
        {props.coffeeStores.length > 0 && (
          <>
            <h2 className={styles.heading2}>
              Arak Coffee Shops
            </h2>
            <div className={styles.cardLayout}>
              {props.coffeeStores.map((coffeeData) => {
                return (
                  <Card
                    key={coffeeData.fsq_id}
                    className={styles.card}
                    href={`./coffee-store/${coffeeData.fsq_id}`}
                    name={coffeeData.name}
                    imgUrl={
                      coffeeData.imgUrl ||
                      "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80"
                    }
                  />
                );
              })}
            </div>
          </>
        )}
      </main>
    </>
  );
}
